---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Hosts

on:
  workflow_call:
    inputs:
      matrix:
        description: "Build matrix from nix-eval-jobs"
        required: true
        type: string

jobs:
  build:
    name: Build ${{ matrix.name }}
    if: ${{ fromJson(inputs.matrix || '{"include":[]}').include[0] != null }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.forgejo/actions/setup-nix
        with:
          attic-endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          attic-cache: ${{ secrets.ATTIC_CACHE }}
          attic-token: ${{ secrets.ATTIC_TOKEN }}
          skip-cache: ${{ forgejo.event.pull_request.head.repo.fork }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Host
        id: build
        uses: ./.forgejo/actions/nix-build
        with:
          target: ${{ matrix.target }}
          build-type: system
          output-link: result

      - name: Post build comment
        if: ${{ always() && forgejo.event_name == 'pull_request' }}
        uses: ./.forgejo/actions/post-build-comment
        with:
          build-type: system
          build-name: ${{ matrix.attr }}
          build-status: ${{ steps.build.outcome }}
          flake-target: ${{ matrix.target }}
          error-log: ${{ steps.build.outputs.error-log }}
          build-duration: ${{ steps.build.outputs.build_duration }}
          runner: ${{ matrix.runner }}
          pr-number: ${{ forgejo.event.pull_request.number }}
