---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Images

on:
  pull_request:
    branches:
      - "test-**"
  push:
    paths:
      - "images"
    branches:
      - "test-**"
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          skip-cache: true
          nothing-but-nix: false

      - name: Get image list
        id: set-matrix
        run: |
          images=$(nix eval --json '.#images' --apply 'builtins.attrNames' | jq -c '{include: map({image: .})}')
          echo "matrix=$images" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.image }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          skip-cache: true
          nothing-but-nix: false

      - name: Garbage collect build dependencies
        run: nix-collect-garbage

      - name: Build ${{ matrix.image }} image
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          set -o pipefail
          nix build \
            ".#images.${IMAGE}" \
            --fallback \
            --log-format raw \
            --print-build-logs

      - name: Find image
        id: find-image
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          image_path=$(find -L result -type f \( -name "*.iso" -o -name "*.qcow2" -o -name "*.img" -o -name "*.raw" \))
          if [ -z "$image_path" ]; then
            echo "No image file found in result/"
            ls -lR result/
            exit 1
          fi
          extension="${image_path##*.}"
          echo "path=$image_path" >> $GITHUB_OUTPUT
          echo "name=nixos-${IMAGE}-$(date -u +"%Y-%m-%d").$extension" >> $GITHUB_OUTPUT

      - name: Upload image
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.find-image.outputs.name }}
          path: ${{ steps.find-image.outputs.path }}
          if-no-files-found: error
          retention-days: 90
