name: Prune Workflows

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  push:
    branches: ["main"]
    paths: [".github/workflows/prune-workflows.yaml"]
  workflow_dispatch:
    inputs:
      successful_runs_to_keep:
        description: "Number of successful runs to keep"
        required: false
        default: "10"
      failed_runs_to_keep:
        description: "Number of failed runs to keep"
        required: false
        default: "5"
      delete_workflow_pattern:
        description:
          "Name or filename of the workflow (if not set, all workflows are
          targeted)"
        required: false
      dry_run:
        description: "Dry run mode (if true, no runs will be deleted)"
        required: false
        type: boolean
        default: false

concurrency:
  group: prune-workflows
  cancel-in-progress: false

jobs:
  prune:
    name: Prune ${{ matrix.conclusion }} runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
    environment:
      name: prod
    strategy:
      fail-fast: false
      matrix:
        include:
          - conclusion: success
            keep_input: successful_runs_to_keep
            default_runs_to_keep: "10"
          - conclusion: failure
            keep_input: failed_runs_to_keep
            default_runs_to_keep: "5"
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Delete old ${{ matrix.conclusion }} workflow runs
        uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee # v2.1.0
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: ${{ inputs[matrix.keep_input] || matrix.default_runs_to_keep }}
          delete_workflow_pattern: ${{ inputs.delete_workflow_pattern }}
          delete_run_by_conclusion_pattern: ${{ matrix.conclusion }}
          dry_run: ${{ inputs.dry_run }}
